//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaPrimerParcial.UnitTest.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PracticaPrimerParcial.WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerimetroTriangulo", ReplyAction="http://tempuri.org/IService1/PerimetroTrianguloResponse")]
        double PerimetroTriangulo(double L1, double L2, double L3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerimetroTriangulo", ReplyAction="http://tempuri.org/IService1/PerimetroTrianguloResponse")]
        System.Threading.Tasks.Task<double> PerimetroTrianguloAsync(double L1, double L2, double L3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreaTriangulo", ReplyAction="http://tempuri.org/IService1/AreaTrianguloResponse")]
        double AreaTriangulo(double L1, double L2, double L3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AreaTriangulo", ReplyAction="http://tempuri.org/IService1/AreaTrianguloResponse")]
        System.Threading.Tasks.Task<double> AreaTrianguloAsync(double L1, double L2, double L3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType GetDataUsingDataContract(PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType> GetDataUsingDataContractAsync(PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PracticaPrimerParcial.UnitTest.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PracticaPrimerParcial.UnitTest.ServiceReference.IService1>, PracticaPrimerParcial.UnitTest.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double PerimetroTriangulo(double L1, double L2, double L3) {
            return base.Channel.PerimetroTriangulo(L1, L2, L3);
        }
        
        public System.Threading.Tasks.Task<double> PerimetroTrianguloAsync(double L1, double L2, double L3) {
            return base.Channel.PerimetroTrianguloAsync(L1, L2, L3);
        }
        
        public double AreaTriangulo(double L1, double L2, double L3) {
            return base.Channel.AreaTriangulo(L1, L2, L3);
        }
        
        public System.Threading.Tasks.Task<double> AreaTrianguloAsync(double L1, double L2, double L3) {
            return base.Channel.AreaTrianguloAsync(L1, L2, L3);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType GetDataUsingDataContract(PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType> GetDataUsingDataContractAsync(PracticaPrimerParcial.UnitTest.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
